# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['net_guardian.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('ui', 'ui'),
        ('core', 'core'),
        ('modules', 'modules'),
        ('utils', 'utils'),
        ('resources', 'resources'),
    ],
    hiddenimports=[
        'customtkinter', 
        'psutil', 
        'speedtest', 
        'matplotlib', 
        'pystray', 
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageTk',
        'tkinter',
        'queue',
        'threading',
        'subprocess',
        'datetime',
        'json',
        'os',
        'sys',
        'time',
        'shutil',
        'socket',
        'logging',
        'collections',
        'ctypes',
        'winreg',
        'winsound',
        'webbrowser',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='NetGuardian',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
)
